version: '3.8'

x-app-common: &app-common
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/app
    - /app/.venv
  environment:
    - PYTHONUNBUFFERED=1
    - NEO4J_URI=bolt://neo4j:7687
    - NEO4J_USER=neo4j
    - NEO4J_PASSWORD=testpassword
  depends_on:
      - neo4j

services:
  neo4j:
    image: neo4j:4.4.0
    environment:
      NEO4J_AUTH: neo4j/testpassword
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j-data:/data
      - ./neo4j-logs:/logs

  app:
    <<: *app-common
    ports:
      - "8080:8080"

  test:
    <<: *app-common
    command: poetry run pytest tests/